### ISSUE TITLE
Does not work for me

### ISSUE THREAD

**Issue by roti** [vegardit/dart-hotreloader#1]
I could not get hotreloader working. Here's my code:
```
void main(List<String> arguments) async {
  final reloader = await HotReloader.create(
      onAfterReload: (ctx) => print('Hot-reload result: ${ctx.result}')
  );

  final app = Server();
  await app.start();
  reloader.stop();
}
```

```
class Server {
  int port = 8888;

  start() async {
    var server = await HttpServer.bind(InternetAddress.loopbackIPv4, port);
    print("Listening to " + port.toString());
    await for (HttpRequest request in server) {
      request.response.write("Hello world");
      await request.response.close();
    }
  }
}
```

I can see the println "Hot-reload result", but the code is not reloaded.

Using Dart 2.12.

**Comment by sebthom** [comment]
Please provide a full example project including pubspec.yml etc. as zip file.

**Comment by roti** [comment]
Here you go: https://drive.google.com/file/d/1TYoCxhcfL7pbQCna0Ka0ohQQLODelm-V/view?usp=sharing

bin/main.dart:
```
import 'package:hotreloader/hotreloader.dart';
import 'package:reloadtest/reload_test.dart';

void main(List<String> arguments) async {
  final reloader = await HotReloader.create(
      onAfterReload: (ctx) => print('Hot-reload result: ${ctx.result}')
  );
  final app = Server();
  await app.start();
  reloader.stop();
}
```

lib/reload_test.dart:
```
import 'dart:io';

class Server {
  int port = 8888;

  start() async {
    var server = await HttpServer.bind(InternetAddress.loopbackIPv4, port);
    print("Listening to " + port.toString());
    await for (HttpRequest request in server) {
      request.response.write("Hello World");
      await request.response.close();
    }
  }
}
```

pubspec.yaml:
```
name: reloadtest
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  hotreloader: ^3.0.0

dev_dependencies:
  pedantic: ^1.9.0
```
